<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="..\..\SharedProperties.props" />

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <Import Project="..\..\..\..\vSharpStudio\Solution.targets" />

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.12" />
    <PackageReference Include="SoloX.CodeQuality.Prod" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
